spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
    generate-ddl: false
    show-sql: true

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

storage:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
    url: jdbc:mysql://${storage.database.core-db.url}
    username: ${storage.database.core-db.username}
    password: ${storage.database.core-db.username}

---


