feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        loggerLevel: FULL
  logging:
    level: DEBUG

---

spring:
  config:
    activate.on-profile: local


external-site:
  sellic:
    host-url: 'http://api.sellic.co.kr/openapi'
    customer_id: '1012'
    api_key: '6790qy09-6642-ac64-zzj3-92jficnw1a50'

  oco:
    id: "TREXI2"
    password: "a1234567"
    host-url: 'https://www.ocokorea.com:9300/api/v1'
    api-key: 'apilive20231011bee'

  buyMa:
    host-url: "https://personal-shopper-api.buyma.com"
    clientId: "pD4b74FBck3F_oEb5G_7hBaCyJyTon64avhsQNIt3-4"
    secretKey: "9Dw-U1QkP3ApEbNXwPgkuMx-56xVuHErgkhSOs3Mu_o"
    code: "2rs8MgoBEJDUfzsMSOnwKRj-mQ8o-fN2glElGMd65c4"
    accessToken: "IotoWQgEm4ZhI7wpa4CmGotb13mh0OimSqVfz9uGOz4"
    refreshToken: "w3kL8eVD1X8cGB0LRUuZIVmMGH1EEu-CI3quZ1VexHs"

  sheIn:
    host-url: "https://openapi.sheincorp.com"
    app-id: "11637FEC1F8038F2B65643B9043C9"
    secret_key: "5DB9EF8014844D60AF51E7FEE10CFFA4"
    open-key-id: "A993C6B7830F4C8988CB2A4C05AB9DE3"
    encoded_secret_key: "t0x/rioCU927JwU3Me2HQ0pgsxzLS32dWbyc01cngLnOx693qmRewgLZNovudQSF"