spring:
  application:
    name: ProductHub
  config:
    import:
      - classpath:logging.yml
      - classpath:db-core.yml
  profiles:
    active: local

#---
#
#spring:
#  profiles: prod
#
#---
#
#spring:
#  profiles: dev
#

---
spring:
  config:
    activate:
      on-profile: local
