spring:
  application:
    name: core-batch
  config:
    import:
      - logging.yml
      - db-core.yml
      - cache-core.yml

  profiles:
    active: local


---
spring:
  config:
    activate:
      on-profile: local