spring:
  config:
    activate.on-profile: test
  data:
    redis:
      host: my-redis
      port: 6379

---

spring:
  config:
    activate.on-profile: local
  data:
    redis:
      port: 6379
      host: localhost

---
